version: "3.8"

services:
  restart: always
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./appdata/html_root:/usr/share/nginx/html:consistent  # Bind mount the local folder for Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ahc_cms

  ahc_cms:
    restart: always
    build:
      context: .  # Build from the root of your project (Gallery_CMS)
      dockerfile: Dockerfile  # Use the Dockerfile in the root directory
    ports:
      - "8080:8080"
    volumes:
      - ./appdata/:/appdata/  # Mount the same folder for Spring Boot to write to
    environment:
      - SPRING_PROFILES_ACTIVE=prod
